### PR TITLE
Support custom screen resolution via define settings when using SDL

### PR DESCRIPTION
**Pull request by imliubo**
1. define M5GFX_WINDOW_WIDTH and M5GFX_WINDOW_HEIGHT to set screen resolution.
2. M5GFX_WINDOW_WIDTH and M5GFX_WINDOW_HEIGHT need to be declared at the same time.

### CODE REVIEW

**Comment by lovyan03** [comment]
What made you need this feature?

**Comment by imliubo** [comment]
I am creating an LVGL simulator based on M5GFX and adding a shell image. Since the sizes of different core device are different, I need to set different window sizes. It will be more convenient to set different simulator window sizes through build_flag.

Demo:
image

build flag:
image

**Comment by lovyan03** [comment]
I understood the purpose.

I'm guessing that your program is setting a special offset on the drawing area to draw the shell image.
I think when the user uses the drawing function, I need to behave in a way that doesn't cause them to draw outside the picture frame.
What you really need is the ability to set the frame, not the width, right?

**Comment by imliubo** [comment]
Yes, the window size and the area rendered by lvgl are implemented through offsets.

The size of the window is set based on the size of the background image. Because I did not find a suitable API to change the default window size, so I added two macro definitions to change the default window size setting by use build_flag...

Core2 backgroud image:
image
CoreS3 backgroud image:
image
Rendering and drawing offset processing:
image

**Comment by lovyan03** [comment]
Is your wish as follows?
- Add new flag to M5GFX build flags to display shell case frames.
- If the display flag of the picture frame is disabled, it will be displayed as before.
- If the display flag of the picture frame is enabled, a dedicated shell case PNG image for each model will be displayed.
- Users cannot interfere with picture frames from M5GFX's drawing function.

**Comment by imliubo** [comment]
Yes! 

It would be best if the user's operations could be limited to the actual display area of the core device (such as the red box part), but the current implementation cannot achieve this.

image

It would be better if the area pointed by the arrow could be made transparent! However, an irregular shell like CoreS3 is a bit difficult to handle.

**Comment by lovyan03** [comment]
It is probably desirable to add new functionality to Panel_SDL. I'm sure SDL can be layered.
In other words, the shell case image is placed in a separate layer from the memory that the user manipulates with drawing functions, and overlapped during SDL rendering.
That way, it would be possible to reproduce a circular display like the M5Dial.

**Comment by lovyan03** [comment]
I will try making a prototype later, so please provide image data of the shell case.

**Comment by imliubo** [comment]
Sure!

[Core2](https://makingfun.oss-cn-qingdao.aliyuncs.com/temp/Core2.png)
- Size: 401 x 401 px
- Display area: (41, 72) - (361, 312)
- X offset: 41
- Y offset: 72

[CoreS3](https://makingfun.oss-cn-qingdao.aliyuncs.com/temp/CoreS3.png)
- Size: 401 x 501 px
- Display area: (41, 123) - (361, 363)
- X offset: 41
- Y offset: 123

**Comment by lovyan03** [comment]
I checked the image, and it looks like the size within the frame is not exactly 320x240, but has an error of 1 pixel. It may be better to correct the error and adjust the size outside the frame to 400x400.

**Comment by imliubo** [comment]
OK, I will ask our art designer check this.

**Comment by imliubo** [comment]
> Sure!
> 
> [Core2](https://makingfun.oss-cn-qingdao.aliyuncs.com/temp/Core2.png)
> 
> * Size: 400 x 400 px
> * Display area: (40, 72) - (360, 312)
> * X offset: 40
> * Y offset: 72
> 
> [CoreS3](https://makingfun.oss-cn-qingdao.aliyuncs.com/temp/CoreS3.png)
> 
> * Size: 400 x 500 px
> * Display area: (40, 122) - (360, 362)
> * X offset: 40
> * Y offset: 122

Updated, please download the image again.

**Comment by lovyan03** [comment]
I think... 
image

**Comment by lovyan03** [comment]
This image was modified by me. I think the top and bottom margins of the actual machine are equal, so I think 80 is preferable instead of 72.

**Comment by imliubo** [comment]
Yes, I asked the hardware engineer and they told me it was equal. I asked the art designer to make changes.

Here is the latest images:
[Core](https://makingfun.oss-cn-qingdao.aliyuncs.com/temp/Core.png)
[Fire](https://makingfun.oss-cn-qingdao.aliyuncs.com/temp/Fire.png)
[Core2](https://makingfun.oss-cn-qingdao.aliyuncs.com/temp/Core2.png)
[CoreS3](https://makingfun.oss-cn-qingdao.aliyuncs.com/temp/CoreS3.png)

**Comment by imliubo** [comment]
Thanks @lovyan03 support, this feature is supported now, so i close this.

**Pull request closed without merging**
